macro(SetPlatform)
    if (CMAKE_HOST_WIN32)
        add_compile_definitions(WINDOWS)
    elseif (CMAKE_HOST_APPLE)
        add_compile_definitions(MACOS)
    elseif (CMAKE_HOST_UNIX)
        add_compile_definitions(LINUX)
    endif ()
    message("add_compile_definitions")
endmacro()